### PR TITLE
fix(CI): use jq in checkimage

### PR DESCRIPTION
**Pull request by petrblaho**
Use jq to query for image digest to remove the need to rely on skopeo inspect output having json keys in particular order. RHINENG-13679

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
@petrblaho This LGTM.  I like this more than grepping and using regex.  The description `...to remove the need to rely on skopeo inspect output...` suggests that `skopeo inspect` will be removed and NOT used at all.  

I am approving it because the current state looks good to me.  If `skopeo inspect` should be removed, please provide the alternate, refresh the PR.  Thanks.

**Comment by petrblaho** [comment]
@thearifismail probably my description is not well worded.... 

`skopeo inspect` output is `json` and `json` object's keys have no defined order in the output. That's why I push for `jq`. Currently we can see more `Digest` keys in `skopeo inspect` output - others are in `LayersData` object. So I want to avoid any possible issues w/r/t ordering of json keys in the output.

**Pull request merged**
