### PR TITLE
[WIP] Case insensitive tag filtering

### PR DESCRIPTION
**Pull request by thearifismail**
This PR implements https://issues.redhat.com/browse/ESSNTL-570

cc: @fijshion

### CODE REVIEW

**Comment by thearifismail** [comment]
@ryandillinfelton can you please take a look?

**Comment by ryandillinfelton** [comment]
I'm jotting down some of what we talked about during our call this morning for our own future reference and the reference of others. The concern we identified was that, while searching is done case insensitively, the results returned are always lowercase. My understanding of the feature request was that it was to be used for typeahead to help users find tags on their hosts to use in filter statements. I believe the filters the tags we return with this query will be used in are case sensitive, which could cause issues. I.E. a user with a host with tag `Sat/key=val` searching with `sat*` would be returned `sat/key=val` which when used in a filter would return no hosts since none have a lowercase `sat` namespace.

If I'm misunderstanding the requirements and use case then please let me know. Otherwise, I  do believe it is possible for us search on the case insensitive versions of the tags, but return the cased versions to users. I just don't know what the actual ES DSL query looks like. Perhaps @fijshion or @jharting would know?

**Comment by fijshion** [comment]
Ah good catch. There's probably another way to structure the query or we might need to modify the mapping. I'll dig into it when I get a chance.

**Comment by fijshion** [comment]
maybe a normalizer will work: https://www.elastic.co/guide/en/elasticsearch/reference/master/normalizer.html.

**Comment by fijshion** [comment]
err - I mean move the normalizer up to the tags_search field instead of creating a new tags_search.lowercase field.

**Comment by fijshion** [comment]
also found this https://github.com/elastic/elasticsearch/issues/68819

**Pull request closed without merging**
