### PR TITLE
ESSNTL-4884: Fixed created and modified times for groups

### PR DESCRIPTION
**Pull request by thearifismail**
This PR fixed the bug reported in [ESSNTL-4884](https://issues.redhat.com/browse/ESSNTL-4884)

### CODE REVIEW

**Comment by fstavela** [comment]
@thearifismail This is from the PR check:
`npm ERR! "npm ci" can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with "npm install" before continuing.`

**Comment by fijshion** [comment]
looks like the package-lock is broken from some recent dependabot updates. Working on fixing it.

**Comment by kruai** [comment]
These field names line up with what's in xjoin-operator. LGTM once the dependency issues are resolved

**Comment by thearifismail** [comment]
> looks like the package-lock is broken from some recent dependabot updates. Working on fixing it.



> looks like the package-lock is broken from some recent dependabot updates. Working on fixing it.

Thank you @fijshion , I have tried using the suggested package version of  `ws` but have not had much success.  Just pushed the latest uisng `"ws": 7.4.6` and see if it works.

**Comment by fijshion** [comment]
#213 replaced this

**Pull request closed without merging**
