### PR TITLE
[Automated] Update mapping

### PR DESCRIPTION
**Pull request by strider**
Updated `xjoin-search` to support the latest `inventory-schemas` changes

image

### CODE REVIEW

**Comment by strider** [comment]
Ok, now `inventory-schemas` directory is still here and the GitHub Action doesn't remove it.

FYI, I've already closed an automatic PR which confirms that the update mapping automation works. We should have now automatic PRs each time the schema is changing in `RedHatInsights/inventory-schemas` repository.

**Comment by strider** [comment]
@fstavela There is a change in the `inventory-schemas` (See screenshot below) and I suppose we need to update the automation tests in `iqe-xjoin-plugin`. I will push an MR asap.
 
image

**Comment by strider** [comment]
Do not merge (DNM) it yet. Some tests should be updated.

**Review by CodeHeeler — APPROVED** [review]
LGTM, I know you're waiting on additional tests though.

**Review by fijshion — APPROVED** [review]

**Pull request merged**
