### PR TITLE
fixed integer range queries with value 0 being ignored

### PR DESCRIPTION
**Pull request by ryandillinfelton**
Small fix. JS evaluates `0` as false. So the checks in the resolver were failing for valid queries. Switched to explicitly check for if the values are null instead. Now queries with 0 work.

### CODE REVIEW

**Comment by fijshion** [comment]
could you switch to use `!==` instead of `!=`?

**Comment by fijshion** [comment]
Looks like there's one more lint error:

```
08:43:26 /srv/volume/jenkins/workspace/RedHatInsights-xjoin-search-pr-check/src/resolvers/inputInt.ts
08:43:26   5:115  error  There should be no space before this paren  space-in-parens
```

FYI the pr checks are working now. They run `npm run verify` (not IQE tests yet).

**Comment by ryandillinfelton** [comment]
> Looks like there's one more lint error:
> 
> ```
> 08:43:26 /srv/volume/jenkins/workspace/RedHatInsights-xjoin-search-pr-check/src/resolvers/inputInt.ts
> 08:43:26   5:115  error  There should be no space before this paren  space-in-parens
> ```
> 
> FYI the pr checks are working now. They run `npm run verify` (not IQE tests yet).

All fixed :+1:

**Comment by ryandillinfelton** [comment]
@fijshion Could I get a re-review on this?

**Comment by ryandillinfelton** [comment]
@fijshion I'd like to get this closed out soon, please take a look when you can.

**Comment by fijshion** [comment]
waiting on app-interface and the PR checks, etc. to be fixed.

**Review by fijshion — APPROVED** [review]

**Pull request merged**
