### PR TITLE
Add per_reporter_staleness filter

### PR DESCRIPTION
**Pull request by kruai**
This is a continuation of PR #85. Adds support for a new flter on per_report_staleness data.

```
filter: {
    per_reporter_staleness: {
        reporter: "yupana"
        stale_timestamp: {gte: "2020-02-10T08:07:03.354307Z"}
        last_check_in: {gte: "2020-02-09T08:07:03.354307Z"}
        check_in_succeeded: {is: true}
    }
}
```

It also changes the mapping to index this data in elastic search correctly, and adds a way to query the new data:

```
data {
    id
    account
    display_name
    per_reporter_staleness {
        reporter
        stale_timestamp
        last_check_in
        check_in_succeeded
    }
}
```

There are also tests to make sure that the filters work correctly.

### CODE REVIEW

**Comment by kruai** [comment]
I'm realizing that this will require some changes to HBI API as well. I'll check those out while this is fresh in my mind.

**Comment by kruai** [comment]
@fijshion The tests are passing in my local environment, but are failing in the PR build... I'm having trouble figuring out what the error messages are trying to tell me, as well. Can I get a hint? :laughing:

**Comment by fijshion** [comment]
@kruai it looks like the version of elasticsearch used in docker-compose is different than the one used in ephemeral pr-checks. The tests pass for me using the docker-compose ES instance, but fail when I use my local (same as ephemeral) ES instance. I had to format the JSON error message to make it easier to see the cause:

```
{
    "response": {
        "errors": [
            {
                "message": "Elastic search error",
                "locations": [
                    {
                        "line": 8,
                        "column": 9
                    }
                ],
                "path": [
                    "hosts"
                ],
                "extensions": {
                    "originalError": {
                        "name": "ResponseError",
                        "meta": {
                            "body": {
                                "error": {
                                    "root_cause": [
                                        {
                                            "type": "x_content_parse_exception",
                                            "reason": "[1:290] [bool] failed to parse field [must]"
                                        }
                                    ],
                                    "type": "x_content_parse_exception",
                                    "reason": "[1:290] [bool] failed to parse field [filter]",
                                    "caused_by": {
                                        "type": "x_content_parse_exception",
                                        "reason": "[1:290] [bool] failed to parse field [must]",
                                        "caused_by": {
                                            "type": "illegal_state_exception",
                                            "reason": "expected value but got [START_ARRAY]"
                                        }
                                    }
                                },
                                "status": 400
                            },
                            "statusCode": 400,
                            "headers": {
                                "content-type": "application/json; charset=UTF-8",
                                "content-length": "422"
                            },
                            "meta": {
                                "context": null,
                                "request": {
                                    "params": {
                                        "method": "POST",
                                        "path": "/test.hosts/_search",
                                        "body": "{\"from\":0,\"size\":10,\"track_total_hits\":true,\"sort\":[{\"display_name.lowercase\":\"ASC\"},{\"id\":\"ASC\"}],\"_source\":[\"id\",\"account\",\"display_name\",\"per_reporter_staleness\"],\"query\":{\"bool\":{\"filter\":[{\"term\":{\"account\":\"test\"}},{\"nested\":{\"path\":\"per_reporter_staleness\",\"query\":{\"bool\":{\"must\":[[{\"term\":{\"per_reporter_staleness.reporter\":\"puptoo\"}}],[{\"term\":{\"per_reporter_staleness.check_in_succeeded\":true}}],[{\"range\":{\"per_reporter_staleness.last_check_in\":{\"lte\":\"2020-01-09T08:07:03.354307Z\"}}}],[{\"range\":{\"per_reporter_staleness.stale_timestamp\":{\"lte\":\"2020-01-10T08:07:03.354307Z\"}}}]]}}}}]}}}",
                                        "querystring": "",
                                        "headers": {
                                            "user-agent": "elasticsearch-js/7.13.0 (linux 3.10.0-1160.59.1.el7.x86_64-x64; Node.js v12.18.3)",
                                            "x-elastic-client-meta": "es=7.13.0,js=12.18.3,t=7.13.0,hc=12.18.3",
                                            "content-type": "application/json",
                                            "content-length": "599"
                                        },
                                        "timeout": 30000
                                    },
                                    "options": {},
                                    "id": 232
                                },
                                "name": "elasticsearch-js",
                                "connection": {
                                    "url": "http://localhost:39001/",
                                    "id": "http://localhost:39001/",
                                    "headers": {},
                                    "deadCount": 0,
                                    "resurrectTimeout": 0,
                                    "_openRequests": 0,
                                    "status": "alive",
                                    "roles": {
                                        "master": true,
                                        "data": true,
                                        "ingest": true,
                                        "ml": false
                                    }
                                },
                                "attempts": 0,
                                "aborted": false
                            }
                        }
                    },
                    "code": "ELASTIC_SEARCH_ERROR"
                }
            }
        ],
        "data": null,
        "status": 200,
        "headers": {}
    },
    "request": {
        "query": "\n    query hosts (\n        $filter: HostFilter,\n        $order_by: HOSTS_ORDER_BY,\n        $order_how: ORDER_DIR,\n        $limit: Int,\n        $offset: Int) {\n        hosts (\n            filter: $filter,\n            order_by: $order_by,\n            order_how: $order_how,\n            limit: $limit,\n            offset: $offset\n        )\n        {\n            data {\n                id,\n                account,\n                display_name,\n                per_reporter_staleness {\n                    reporter,\n                    last_check_in,\n                    stale_timestamp,\n                    check_in_succeeded\n                }\n            }\n        }\n    }\n",
        "variables": {
            "filter": {
                "per_reporter_staleness": {
                    "reporter": {
                        "eq": "puptoo"
                    },
                    "last_check_in": {
                        "lte": "2020-01-09T08:07:03.354307Z"
                    },
                    "stale_timestamp": {
                        "lte": "2020-01-10T08:07:03.354307Z"
                    },
                    "check_in_succeeded": {
                        "is": true
                    }
                }
            }
        }
    }
}
```
and here is the Elasticsearch requests:

```
{
    "from": 0,
    "size": 10,
    "track_total_hits": true,
    "sort": [
        {
            "display_name.lowercase": "ASC"
        },
        {
            "id": "ASC"
        }
    ],
    "_source": [
        "id",
        "account",
        "display_name",
        "per_reporter_staleness"
    ],
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "account": "test"
                    }
                },
                {
                    "nested": {
                        "path": "per_reporter_staleness",
                        "query": {
                            "bool": {
                                "must": [
                                    [
                                        {
                                            "term": {
                                                "per_reporter_staleness.reporter": "puptoo"
                                            }
                                        }
                                    ],
                                    [
                                        {
                                            "term": {
                                                "per_reporter_staleness.check_in_succeeded": true
                                            }
                                        }
                                    ],
                                    [
                                        {
                                            "range": {
                                                "per_reporter_staleness.last_check_in": {
                                                    "lte": "2020-01-09T08:07:03.354307Z"
                                                }
                                            }
                                        }
                                    ],
                                    [
                                        {
                                            "range": {
                                                "per_reporter_staleness.stale_timestamp": {
                                                    "lte": "2020-01-10T08:07:03.354307Z"
                                                }
                                            }
                                        }
                                    ]
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

I don't think the `must` clause can be an array of arrays.

**Comment by fijshion** [comment]
I just pushed a commit to update the docker-compose ES version to be the same as ephemeral which produces the same errors as the PR check.

**Comment by kruai** [comment]
Ah, thanks. I copied and pasted the `must` part from the original PR, and am afraid I didn't give it too thorough of a look when it seemed to work. I'll get it updated!

**Comment by kruai** [comment]
OK - after looking up the way `must` is supposed to work, I opted for concatenating the arrays. LMK if there's a better way to do it!

**Pull request merged**
