### PR TITLE
made fqdn use lowercase operations

### PR DESCRIPTION
**Pull request by ryandillinfelton**
On HBI we switched over to querying for fqdn in lowecase prematurely, we are getting lots of 400 errors from xjoin-search because of this. This PR will fix that by switching fqdn to using all lowercase operations.

refer the the PR that introduced the bug here for the reasoning behind the change: https://github.com/RedHatInsights/insights-host-inventory/pull/956

### CODE REVIEW

**Comment by ryandillinfelton** [comment]
Any idea why the check is failing? The error mentions yargs not supporting the current version of nodeJS, but I didn't touch anything related to that afaik, so I'm not sure what's up. Haven't been able to reproduce the issue locally either.

**Comment by kruai** [comment]
@fijshion @jharting any idea what's going on here? This bug is blocking some stuff on the HBI side

**Comment by fijshion** [comment]
@kruai I manually tested and have some questions for @ryandillinfelton. DM'd him in slack.

**Comment by fijshion** [comment]
@kruai nvm - he's on PTO. I'll see if I can get this to work. Just to double check, the intention of this PR is to be able to filter by fqdn ignoring case? So this filter

```
{
  hosts (
    filter: {
      fqdn: {eq_lc: "FQDN.test01.rhel7.jharting.local"}
    },
    order_by: display_name,
    order_how: ASC,
    limit: 10,
    offset: 0
  ) {
    meta { count, total }
    data {
      id
      canonical_facts
    }
  }
}
```

Should match this host:

```
{
  "data": {
    "hosts": {
      "meta": {
        "count": 1,
        "total": 1
      },
      "data": [
        {
          "id": "6e7b6317-0a2d-4552-a2f2-b7da0aece49d",
          "canonical_facts": {
            "provider_type": "aws",
            "fqdn": "fqdn.test01.rhel7.jharting.local",
            "satellite_id": "ce87bfac-a6cb-43a0-80ce-95d9669db71f",
            "insights_id": "a58c53e0-8000-4384-b902-c70b69faacc5",
            "provider_id": "1d073c47-8467-4372-b585-7b0d40d2ee3c"
          }
        }
      ]
    }
  }
}
```

That isn't working for me locally. I'll see if I can get it working.

**Comment by kruai** [comment]
@fijshion That's correct. For context, HBI has started sending `matches_lc` instead of `matches` for FQDN, which caused some unexpected errors from xjoin; the goal is to resolve that issue and make FQDN case-insensitive overall.

**Comment by fijshion** [comment]
Just needed to update the ES mapping to support the lowercase filter: https://github.com/RedHatInsights/xjoin-operator/commit/e7fadc7ac9c5c3d55f097f739d008f5a811f195f.

**Comment by kruai** [comment]
Fantastic! Thank you :)

**Pull request merged**
